style: github
template: CHANGELOG.tpl.md
info:
  title: CHANGELOG
  repository_url: https://github.com/rsHalford/tag
options:
  commits:
    filters:
      Type:
        - feat
        - fix
        - refactor
        - style
        - theme
        - test
        - perf
        - ci
        - chore
  commit_groups:
    title_maps:
      feat: Features
      fix: Bug Fixes
      refactor: Code Refactoring
      style: Styling
      theme: Theme
      test: Testing
      perf: Performance Improvements
      ci: CI
      chore: Chores
  header:
    pattern: "^(\\w*)(?:\\(([\\w\\$\\.\\-\\*\\s]*)\\))?\\:\\s(.*)$"
    pattern_maps:
      - Type
      - Scope
      - Subject
  notes:
    keywords:
      - BREAKING CHANGE
